export const defaultErrorsLead = {
  lead: {
    loan_type: null,
    purpose_of_loan: null,
    property_type: null,
    applied_amount: null,
  },

  property_details: {
    property_identification_is: null,
    property_value_estimate: null,
    current_owner_name: null,
    plot_house_flat: null,
    project_society_colony: null,
    pincode: null,
  },

  reference_details: {
    reference_1_type: null,
    reference_1_full_name: null,
    reference_1_phone_number: null,
    reference_1_address: null,
    reference_1_pincode: null,
    reference_1_email: null,
    reference_2_type: null,
    reference_2_full_name: null,
    reference_2_phone_number: null,
    reference_2_address: null,
    reference_2_pincode: null,
    reference_2_email: null,
  },

  addressSchema: {
    current_type_of_residence: null,
    current_flat_no_building_name: null,
    current_street_area_locality: null,
    current_town: null,
    current_landmark: null,
    current_pincode: null,
    current_no_of_year_residing: null,
    additional_type_of_residence: null,
    additional_flat_no_building_name: null,
    additional_street_area_locality: null,
    additional_town: null,
    additional_landmark: null,
    additional_pincode: null,
    additional_no_of_year_residing: null,
    address_for_tax_purpose:null
  },

  work_income_detail: {
    profession: null,
    company_name: null,
    salary_per_month: null,
    pf_uan: null,
    no_current_loan: null,
    ongoing_emi: null,
    working_since: null,
    mode_of_salary: null,
    flat_no_building_name: null,
    street_area_locality: null,
    town: null,
    landmark: null,
    pincode: null,
    city: null,
    state: null,
    total_family_number: null,
    total_household_income: null,
    no_of_dependents: null,
    business_name: null,
    industries: null,
    gst_number: null,
    pention_amount: null,
    extra_params: {
      extra_company_name: null,
      extra_industries: null,
    },
    monthly_income:null
  },

  applicants: [],
};
