export const property_Data = [
    {
      row: 1,
      propertyCategory: 'Authority',
      authorityName: 'Delhi Development Authority (DDA)',
      typeOfProperty: 'Freehold',
      PTT: 'Allotment Transfer',
      PP: [
        'Allotment Letter',
        'Allotment Transfer Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 2,
      propertyCategory: 'Authority',
      authorityName: 'Delhi Development Authority (DDA)',
      typeOfProperty: 'Freehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 3,
      propertyCategory: 'Authority',
      authorityName: 'Delhi Development Authority (DDA)',
      typeOfProperty: 'Freehold',
      PTT: 'Resale',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'ATS / Sale deed in favour of customer',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'NOC from competent authority (if applicable)',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
    {
      row: 4,
      propertyCategory: 'Authority',
      authorityName: 'Delhi Development Authority (DDA)',
      typeOfProperty: 'Leasehold',
      PTT: 'Allotment Transfer',
      PP: [
        'Allotment Letter',
        'Allotment Transfer Letter',
        'PTM/Acknowlegement of Mortgage',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 5,
      propertyCategory: 'Authority',
      authorityName: 'Delhi Development Authority (DDA)',
      typeOfProperty: 'Leasehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'PTM/Acknowlegement of Mortgage',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 6,
      propertyCategory: 'Authority',
      authorityName: 'Delhi Development Authority (DDA)',
      typeOfProperty: 'Leasehold',
      PTT: 'Resale',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'ATS / Sale deed in favour of customer',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'NOC from competent authority (if applicable)',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
    {
      row: 7,
      propertyCategory: 'Authority',
      authorityName: 'Land and Development Office (LNDO)',
      typeOfProperty: 'Freehold',
      PTT: 'Allotment Transfer',
      PP: [
        'Allotment Letter',
        'Allotment Transfer Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 8,
      propertyCategory: 'Authority',
      authorityName: 'Land and Development Office (LNDO)',
      typeOfProperty: 'Freehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 9,
      propertyCategory: 'Authority',
      authorityName: 'Land and Development Office (LNDO)',
      typeOfProperty: 'Freehold',
      PTT: 'Resale',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'ATS / Sale deed in favour of customer',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'NOC from competent authority (if applicable)',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
    {
      row: 10,
      propertyCategory: 'Authority',
      authorityName: 'Land and Development Office (LNDO)',
      typeOfProperty: 'Leasehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'PTM/Acknowlegement of Mortgage',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
      ],
    },
    {
      row: 11,
      propertyCategory: 'Authority',
      authorityName: 'Land and Development Office (LNDO)',
      typeOfProperty: 'Leasehold',
      PTT: 'Resale',
      PP: [
        'Allotment Letter',
        'Possession Letter',
        'GPA Chain (if any)',
        'PTM/Acknowlegement of Mortgage',
        'Lease Deed Excecuted by Authority',
        'Transfer Deed from Competent Authority (if applicable)',
        'ATS / Sale deed in favour of customer',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'NOC from competent authority (if applicable)',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
    {
      row: 12,
      propertyCategory: 'Society',
      authorityName: null,
      typeOfProperty: 'Freehold',
      PTT: 'Allotment Transfer',
      PP: [
        'Allotment Letter',
        'Allotment Transfer Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Jamabandi / Mutation',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
      ],
    },
    {
      row: 13,
      propertyCategory: 'Society',
      authorityName: null,
      typeOfProperty: 'Freehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Jamabandi / Mutation',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
      ],
    },
    {
      row: 14,
      propertyCategory: 'Society',
      authorityName: null,
      typeOfProperty: 'Freehold',
      PTT: 'Resale',
      PP: [
        'Allotment Letter',
        'Possession Letter',
        'GPA Chain (if any)',
        'ATS / Sale deed in favour of customer',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'Lease Deed Excecuted by Authority',
        'NOC from competent authority (if applicable)',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
    {
      row: 15,
      propertyCategory: 'Society',
      authorityName: null,
      typeOfProperty: 'Leasehold',
      PTT: 'Allotment Transfer',
      PP: [
        'Allotment Letter',
        'Allotment Transfer Letter',
        'PTM/Acknowlegement of Mortgage',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Jamabandi / Mutation',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
      ],
    },
    {
      row: 16,
      propertyCategory: 'Society',
      authorityName: null,
      typeOfProperty: 'Leasehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'PTM/Acknowlegement of Mortgage',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Jamabandi / Mutation',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
      ],
    },
    {
      row: 17,
      propertyCategory: 'Society',
      authorityName: null,
      typeOfProperty: 'Leasehold',
      PTT: 'Resale',
      PP: [
        'Allotment Letter',
        'Possession Letter',
        'GPA Chain (if any)',
        'PTM/Acknowlegement of Mortgage',
        'ATS / Sale deed in favour of customer',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'NOC from competent authority (if applicable)',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
    {
      row: 18,
      propertyCategory: 'Builder',
      authorityName: null,
      typeOfProperty: 'Freehold',
      PTT: 'Allotment Transfer',
      PP: [
        'Allotment Letter',
        'Allotment Transfer Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
      ],
    },
    {
      row: 19,
      propertyCategory: 'Builder',
      authorityName: null,
      typeOfProperty: 'Freehold',
      PTT: 'Direct Allotment',
      PP: [
        'Allotment Letter',
        'Payment Receipts',
        'Outstanding Demand letter',
        'Undertaking to submit Original Possession letter & Title deed (as an when executed)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'Occupancy Certificate',
      ],
    },
    {
      row: 20,
      propertyCategory: 'Khasra',
      authorityName: null,
      typeOfProperty: 'Freehold',
      PTT: 'Transfer and Sale',
      PP: [
        'Khatoni/ROR',
        'GPA Chain (if any)',
        'ATS / Sale deed in favour of customer',
        'Original Proposed Deed/Co-Ownership/Gift/Release Deed/Conveyance Deed/Relinquishment deed/Title deed',
        'Probate Order (if applicable)',
        'Property Tax receipt / Ebill / Any other Possession Proof (if Delivered Property)',
        'NOC from competent authority (if applicable)',
        'Mouka Patwari Report / Nazari Naksha',
        'Hissa Bandi Repost',
        'Lal Dora Certificate',
        'Family Affidavit',
        'Bail / Surety Discharge (If applicable)',
        'Deed of Partition',
      ],
    },
  ];